Add the capability for a client to incrementally transfer vf axis space
w3c/IFT pull request #11
Opened 2021-07-21 21:58 UTC by garretrieger

Similar to codepoints this adds an axis space have and axis space needed to the request. This allows a client to get a subset of the font with a reduced axis space and then later on expand the axis space via a patch.

2021-07-27 17:51 UTC, vlevantovsky commented on Overview.bs
> +    then this interval is a single point, <code>start</code>.
Minor correction: should probably be "`end` is optional"

2021-07-27 18:15 UTC, vlevantovsky commented on Overview.bs
>  A server is free to choose any codepoint ordering, but should try to pick one that will minimize the
General comment: one thing I noticed is that the current version of the spec seem to be written as a document that describes a particular PFE implementation. The alternative way is to describe what implementations [must / must not / should / should not] do, and all these requirement need to be clearly identified as normative (and, therefore, testable).
If something is expected to be done a particular way (e.g. checksum calculation below), it needs to be defined as normative - the difference is whether something can be done this way or MUST be done this way.

2021-07-27 18:23 UTC, vlevantovsky requested changes
The changes related to VF axis space are fine, but overall - the more language is added, the harder it gets to make the text of the spec normative. There are quite a few "must" used as part of the descriptive text, and some of them are likely testable and need to be made normative (i.e., we need to use "MUST" instead, e.g. when we specify what it means for an object to be "well-formed").

2021-07-28 15:52 UTC, svgeesus approved these changes
This all looks good to me.

2021-07-28 15:55 UTC, svgeesus commented
> 
> 
> The changes related to VF axis space are fine, but overall - the more language is added, the harder it gets to make the text of the spec normative. There are quite a few "must" used as part of the descriptive text, and some of them are likely testable and need to be made normative (i.e., we need to use "MUST" instead, e.g. when we specify what it means for an object to be "well-formed").

Yes, good point. In the WOFF 1 and 2 specifications we marked up individual testable statements, so that they could be linked to from tests (and so that we could do test coverage analysis).

That isn't needed for First Public Working Draft but will be needed down the line.

2021-07-28 18:59 UTC, vlevantovsky commented
> That isn't needed for First Public Working Draft but will be needed down the line.

Agree. My only concern was that the more language is added, the more work it will be going back to revise it. By capitalizing "musts" that represent testable requirements we will at least reduce the time needed to update the spec later.

2021-07-30 22:58 UTC, garretrieger commented
> > That isn't needed for First Public Working Draft but will be needed down the line.
> 
> Agree. My only concern was that the more language is added, the more work it will be going back to revise it. By capitalizing "musts" that represent testable requirements we will at least reduce the time needed to update the spec later.

In the "Document Conventions" section we state: "However, for readability, these words do not appear in all uppercase letters in this specification."  so I've been intentionally not capitalizing the should/must/should nots/must nots, but wherever I use must/should I've generally done so intentionally with the meaning from the definitions here: https://datatracker.ietf.org/doc/html/rfc2119

2021-07-30 23:00 UTC, garretrieger commented
> > > That isn't needed for First Public Working Draft but will be needed down the line.
> > 
> > 
> > Agree. My only concern was that the more language is added, the more work it will be going back to revise it. By capitalizing "musts" that represent testable requirements we will at least reduce the time needed to update the spec later.
> 
> In the "Document Conventions" section we state: "However, for readability, these words do not appear in all uppercase letters in this specification." so I've been intentionally not capitalizing the should/must/should nots/must nots, but wherever I use must/should I've generally done so intentionally with the meaning from the definitions here: https://datatracker.ietf.org/doc/html/rfc2119

If we're going to use capitalized keywords then let's remove that sentence from the document conventions as well.

2021-08-02 14:32 UTC, vlevantovsky commented
> In the "Document Conventions" section we state: "However, for readability, these words do not appear in all uppercase letters in this specification." so I've been intentionally not capitalizing the should/must/should nots/must nots, but wherever I use must/should I've generally done so intentionally with the meaning from the definitions here: https://datatracker.ietf.org/doc/html/rfc2119

Ah, thank you, I completely missed this point. I was not aware the established process would allow us to essentially redefine RFC 2119 keywords from capitalized to lowercase, and didn't pay much attention to formal parts of the spec.

> If we're going to use capitalized keywords then let's remove that sentence from the document conventions as well.

I guess this is a question for Chris - can we redefine the RFC2119 keywords to have the same meaning when they are used in lowercase? If yes, then everything will stay the same and no further changes are needed. If however, the keywords must be capitalized (my expectation was that this is the case), then we would need to make changes at some point of document development.

2021-08-02 14:32 UTC, vlevantovsky approved these changes

2021-08-03 23:32 UTC, merged