Add a note warning about the dangers of subsetter upgrades
w3c/IFT pull request #39
Opened 2021-10-19 23:55 UTC by garretrieger

when a patch subset service is composed of multiple tasks.

Fixes #29

2021-10-20 17:59 UTC, svgeesus requested changes

2021-10-20 17:59 UTC, svgeesus commented on Overview.bs
> +subset. This scenario is may to occur during software updates to the server tasks. To combat this
is may to occur => might occur

2021-11-04 16:48 UTC, svgeesus approved these changes
Looks great

2021-11-04 19:23 UTC, garretrieger commented on Overview.bs
> +it's recommended that sticky load balancing is used which aims to send consecutive requests from the
I would think not everyone running a small service would be familiar, but I would expect someone who's running a large fleet of tasks to be familiar with the concept. Which is who this advice is targeted too.

2021-11-05 19:01 UTC, merged